Algoritmo ""
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Huelton Santos
// Descrição   : "Verificação de região e temperatura"
// Autor(a)    : Elaine Macedo
// Data atual  : 14/01/2021
Var
   // Seção de Declarações das variáveis
        temperatura: real
        regiao: caractere


Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
    escreval ("Informe a região: <ENTER>")
    leia (temperatura)

Fimalgoritmo